# Generated by Django 3.2.18 on 2023-05-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address',
            new_name='street_address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='town_or_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='original_bag',
        ),
        migrations.AddField(
            model_name='order',
            name='street_address2',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
